
import Head from 'next/head'
import styles from '@/styles/forgotpass.module.css'
import Link from 'next/link'
import React, {useState } from 'react'
import Axios from 'axios' 
import {useRouter} from 'next/router';

function NewPass() {
  const router = useRouter()
  const get_email = router.query.email
  const [changePass, setPass] = useState('')
  const [changeRepass, setRepass] = useState('')
  const [changeStatuseErr, changeRegstaterr] = useState('')
  
  const change = (e) =>{
    e.preventDefault()
      Axios.post('http://localhost:4000/change',{
        email: get_email,
        password: changePass,
        repass: changeRepass
      }).then((response)=>{
        console.log(response)
        if (response.data.message == "Successfully Reset Password"){
          window.location.href='./'
        }else{
          changeRegstaterr(response.data.message)
        }
        
      })
  
  
    };
  return (
    <>
      <Head>
        <title>Forgot Password</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.contentbody}>
            <div className= {styles.top} >
            Reset Your Password
            </div>
            <h3 className='text-danger'>{changeStatuseErr}</h3>

            <div className= {styles.low} >
                <form className= {styles.FormDetails}>
                    <div className={styles.FPDetails}>
                        <div className={styles.FPLabels}>
                        New Password:
                        </div>
                        <input type="password" className={styles.FPInputs} required onChange={(e)=>{setPass(e.target.value);}} />
                    </div>
                    <div className={styles.FPDetails}>
                        <div className={styles.FPLabels}>
                        Confirm Password:
                        </div>
                        <input type="password" className={styles.FPInputs} required onChange={(e)=>{setRepass(e.target.value);}} />
                    </div>
                    <input type='submit' value= 'Submit' className={styles.submitbttn} onClick= {change}/>
                </form>
            </div>
        </div>
      </main>
    </>
  )
}
export default NewPass